name: Tests

on:
  push:
    paths-ignore:
      - "*.md"
    branches-ignore:
      - master
  workflow_call:

jobs:
  test:
    runs-on: buildjet-2vcpu-ubuntu-2204
    strategy:
      matrix:
        nim:
          - "1.6.x"
          - "2.0.x"
          - "2.2.x"
          - "devel"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache nimble
        id: cache-nimble
        uses: buildjet/cache@v3
        with:
          path: ~/.nimble
          key: ${{ matrix.nim }}-nimble-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ matrix.nim }}-nimble-
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nimble build -d:release -Y
      - run: pip install seleniumbase
      - run: seleniumbase install chromedriver
      - uses: supercharge/redis-github-action@1.5.0
      - name: Prepare Nitter
        run: |
          sudo apt install libsass-dev -y
          cp nitter.example.conf nitter.conf
          sed -i 's/enableDebug = false/enableDebug = true/g' nitter.conf
          nimble md
          nimble scss
          echo '${{ secrets.SESSIONS }}' > ./sessions.jsonl
      - name: Run tests
        run: |
          ./nitter &
          pytest -n3 tests
